apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurent-service-config
  namespace: smartdelivery
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "RestaurantDatabase": "Data Source=.;Initial Catalog=RestaurentServiceDb;Integrated Security=True;TrustServerCertificate=True;"
      },
      "Jwt": {
        "Issuer": "SmartOrderSystem",
        "Audience": "SmartOrderSystemUsers",
        "SecretKey": "VerySecretKeyForSigningTokens123!"
      },
      "Serilog": {
        "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.Elasticsearch" ],
        "MinimumLevel": {
          "Default": "Information",
          "Override": {
            "Microsoft": "Warning",
            "System": "Warning"
          }
        },
        "WriteTo": [
          {
            "Name": "Console"
          },
          {
            "Name": "Elasticsearch",
            "Args": {
              "nodeUris": "http://localhost:9200",
              "indexFormat": "orderservice-logs-{0:yyyy.MM}",
              "autoRegisterTemplate": true
            }
          }
        ],
        "Enrich": [ "FromLogContext" ]
      }
    }
