apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurent-service-config
  namespace: smartdelivery
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "RestaurantDatabase": "PLACEHOLDER_DB_CONNECTION_STRING"
      },
      "Jwt": {
        "Issuer": "PLACEHOLDER_JWT_ISSUER",
        "Audience": "PLACEHOLDER_JWT_AUDIENCE",
        "SecretKey": "PLACEHOLDER_JWT_SECRET_KEY"
      },
      "Elasticsearch": {
        "Uri": "PLACEHOLDER_ELASTICSEARCH_URI",
        "Username": "elastic",
        "Password": "yourpassword"
     },
      "Serilog": {
        "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.Elasticsearch" ],
        "MinimumLevel": {
          "Default": "Information",
          "Override": {
            "Microsoft": "Warning",
            "System": "Warning"
          }
        },
        "WriteTo": [
          {
            "Name": "Console"
          },
          {
            "Name": "Elasticsearch",
            "Args": {
              "nodeUris": "PLACEHOLDER_ELASTICSEARCH_URI",
              "indexFormat": "orderservice-logs-{0:yyyy.MM}",
              "autoRegisterTemplate": true
            }
          }
        ],
        "Enrich": [ "FromLogContext" ]
      }
    }
