apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-api
  namespace: helmtest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
      - name: api
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        ports:
        - containerPort: 8080  # Must match app's listening port
        envFrom:
        - configMapRef:
            name: dotnet-config
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"