apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-service-config
  namespace: smartdelivery
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "CartDatabase": "__CART_DB_CONNECTION__"
      },
      "ServiceName": "CartService"
    }
