apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: smartdelivery
  labels:
    app: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: cart-service
        image: ghcr.io/prakashrajansakthivel/cartservice:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
      volumes:
      - name: config-volume
        configMap:
          name: cart-service-config
