apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: smartdelivery
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "OrderDatabase": "__ORDER_DB_CONNECTION__"
      },
      "Jwt": {
        "Issuer": "SmartOrderSystem",
        "Audience": "SmartOrderSystemUsers",
        "SecretKey": "VerySecretKeyForSigningTokens123!"
      },
      "Elasticsearch": {
        "Uri": "http://elasticsearch-service:9200",
        "Username": "elastic",
        "Password": "yourpassword"
      },
      "RestaurantService": {
        "BaseUrl": "http://restaurent-service:8080"
      },
      "Serilog": {
        "Using": [ "Serilog.Sinks.Console", "Serilog.Sinks.Elasticsearch" ],
        "MinimumLevel": {
          "Default": "Information",
          "Override": {
            "Microsoft": "Warning",
            "System": "Warning",
            "Microsoft.AspNetCore": "Information"
          }
        },
        "WriteTo": [
          {
            "Name": "Console"
          },
          {
            "Name": "Elasticsearch",
            "Args": {
              "nodeUris": "http://elasticsearch-service:9200",
              "indexFormat": "orderservice-logs-{0:yyyy.MM}",
              "autoRegisterTemplate": true,
              "batchPostingLimit": 10,
              "period": 2,
              "inlineFields": true,
              "bufferBaseFilename": "./logs/elasticsearch-buffer",
              "emitEventFailure": "WriteToSelfLog",
              "queueSizeLimit": 10000
            }
          }
        ],
        "Enrich": [ "FromLogContext", "WithMachineName", "WithProcessId" ],
        "Properties": {
          "Application": "OrderService",
          "Environment": "Production"
        }
      },
      "ServiceName": "OrderService"
    }
