apiVersion: v1
kind: Config
clusters:
- name: default
  cluster:
    server: https://46.62.150.44:6443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzTlRVeU16ZzVOekl3SGhjTk1qVXdPREUxTURZeU1qVXlXaGNOTXpVd09ERXpNRFl5TWpVeQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzTlRVeU16ZzVOekl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTa1FvNXN0enllL1k0QkZNM2l2OGgzRUV4M0tBT1MweWtHUnlXK2NPMnIKMjlCTVpaR2VJc25OUTBhdVBITnoxODN3djdUcmswNWJTZWxiTkdQc0JEdTJvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUNCZG9KSUJoNjFJbHBCWDZmRXljCnRJSGNPSnd3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQU5XZTZTVGhVS1JoNE93TW05Tm5CN0p3emVtQU41aFAKUWVFYzFsNFVGaFhkQWlFQTFFSHpUTVNHbXpWNzF2bVdsSjdEeGFmSzFWYk4ra0toOUdvOHNSVTB6L009Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
users:
- name: gha-deployer
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkNNWW4yNWN5ajVNU2dhN2wzRHEwUnZvUG1QMFlNQlN1YjV0TE9Cd2N0azgifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzU2Mjg2NjQ1LCJpYXQiOjE3NTYyODMwNDUsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZmY1YzU3MmQtM2Q1Yy00NmNhLWFkZTMtN2E3N2JmZjA5NDVlIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJnaGEtZGVwbG95ZXIiLCJ1aWQiOiJiZWRiMDkzNC0xNzVlLTRhMzktODM5Mi0wMzJhMGNkNTVlM2YifX0sIm5iZiI6MTc1NjI4MzA0NSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmdoYS1kZXBsb3llciJ9.h3HFqDNC3I0_NgLsmhteFTkQNO98IX55KXkfMBCFl-GsQurCdzJriCIyAxQVouxUAoACcOoTLrhS_J35Llz15vX4FY7rJMF0yaTbEhFPaN47wde7jAwtVBvrzYs0QZ8vnI56c1pzzEMDdX6xB4bHljmU6d7HkQLjcfTZvA9gJny18dscnZF0IwaE9JHe-_WXfaXVG_nqWMsIlpeKl3P4pYey5hhaUhJpNCRIL5fdXQc5w2QeJnZanVRLxsKdEDvlmXmTu4nM5xldYZoEss4G7LRpaJPghQgxSPuKSaGpAiB5obmdk2iNMaG8IJYb4BHJ3aLWqdVFMxJe54faacnbfQ
contexts:
- name: gha-context
  context:
    cluster: default
    user: gha-deployer
current-context: gha-context
