name: Build and Push Restaurant Service

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'
  push:
    branches:
      - main
      - feature/pipeline-init

jobs:
  build-and-push:
    uses: ./.github/workflows/build-service-reusable.yml
    secrets: inherit
    with:
      service_display_name: Restaurant Service
      source_ref: feature/buildfix
      project_path: src/services/RestaurantService/Restaurant.API/RestaurantService.API.csproj
      service_folder: RestaurantService
      dll_name: RestaurantService.API.dll
      dockerfile_name: restaurentservice
      image_tag: ghcr.io/prakashrajansakthivel/smartdeliveryinfra/restaurentservice:${{ github.run_id }}
      remove_default_appsettings: true
