name: Build and Push Payment Service

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '20 0 * * *'
  push:
    branches:
      - main
      - feature/pipeline-init

jobs:
  build-and-push:
    uses: ./.github/workflows/build-service-reusable.yml
    secrets: inherit
    with:
      service_display_name: Payment Service
      source_ref: feature/buildfix
      project_path: src/services/PaymentService/PaymentService.API/PaymentService.API.csproj
      service_folder: PaymentService
      dll_name: PaymentService.API.dll
      dockerfile_name: paymentservice
      image_tag: ghcr.io/prakashrajansakthivel/paymentservice:${{ github.run_id }}
