name: Database Migration Pipeline

on:
  workflow_dispatch:
    inputs:
      code_ref:
        description: 'SmartDelivery branch/tag to use'
        required: true
        default: 'feature/pipeline-init'
      migrate_restaurant:
        description: 'Run Restaurant DB migration'
        type: boolean
        default: true
      migrate_order:
        description: 'Run Order DB migration'
        type: boolean
        default: true
      migrate_cart:
        description: 'Run Cart DB migration'
        type: boolean
        default: true

jobs:
  migrate-databases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v4

      - name: Checkout Code Repo
        uses: actions/checkout@v4
        with:
          repository: PrakashRajanSakthivel/SmartDelivery
          ref: ${{ inputs.code_ref }}
          token: ${{ secrets.CODE_REPO_TOKEN }}
          path: SmartDelivery

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install EF Core CLI
        run: |
          dotnet tool install --global dotnet-ef
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Apply Restaurant DB migrations
        if: ${{ inputs.migrate_restaurant }}
        uses: ./.github/actions/ef-migrate
        with:
          working_directory: SmartDelivery/src/services/RestaurantService/RestaurantService.Infra
          project: RestaurantService.Infra.csproj
          startup_project: ../Restaurant.API/RestaurantService.API.csproj
          context: RestaurantDbContext
          connection: ${{ secrets.RESTAURANT_DB_CONNECTION_STRING }}

      - name: Apply Order DB migrations
        if: ${{ inputs.migrate_order }}
        uses: ./.github/actions/ef-migrate
        with:
          working_directory: SmartDelivery/src/services/OrderService/OrderService.Infra
          project: OrderService.Infra.csproj
          startup_project: ../OrderService.API/OrderService.API.csproj
          context: OrderDbContext
          connection: ${{ secrets.ORDER_DB_CONNECTION_STRING }}

      - name: Apply Cart DB migrations
        if: ${{ inputs.migrate_cart }}
        uses: ./.github/actions/ef-migrate
        with:
          working_directory: SmartDelivery/src/services/CartService/CartService.Infra
          project: CartService.Infra.csproj
          startup_project: ../CartService.API/CartService.API.csproj
          context: CartDbContext
          connection: ${{ secrets.CART_DB_CONNECTION_STRING }}
