name: Test Kubernetes Connection

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dockerbuilds
      - '**'  # matches all branches

jobs:
  test-connect:
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Write kubeconfig from secret
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig

      - name: Open Hetzner Firewall port 6443 to all IPs
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          FIREWALL_ID: ${{ secrets.FIREWALL_ID }}
        shell: pwsh
        run: |
          .\base\open-firewall-port.ps1 -Port 6443 -Description "Open Kubernetes API for CI/CD"

      - name: Test connection to cluster
        run: |
          kubectl --kubeconfig=kubeconfig get ns

      - name: Close Hetzner Firewall port 6443 to all IPs
        if: always()
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          FIREWALL_ID: ${{ secrets.FIREWALL_ID }}
        shell: pwsh
        run: |
          .\base\close-firewall-port.ps1 -Port 6443
